### ISSUE TITLE
refactor: Consider moving too a fully typed error

### ISSUE THREAD

**Issue by dvdsk** [aschey/stream-download-rs#15]
As a lib author and user I strongly prefer fully typed errors that I can easily match on. std's io::Error provides this through the std::io::ErrorKind enum. We however can not extend that here.

The current WrapIoResult trait approach makes a ton of sense for a lot of the existing code (opening files etc) but we can get more expressive.

I realize this would be a lot of work. As a middle ground how would you feel about adding an associate type to StorageProvider and leaving it to io::Error for now while working upstream in Lib to move away from std::io::Error?

**Comment by aschey** [comment]
Yes, I admit I was a bit lazy here since the vast majority of errors we deal with are IO errors, it was easier to just keep propagating it that way. Especially since the vast majority of errors are going to be encountered in the background task and won't be seen by the caller. Adding some associated error types to the traits here is probably a good idea, I'd be okay with that.

**Comment by dvdsk** [comment]
You got a good point there regarding the background tasks. Ill have a look if I can work some in my code without it spreading like a virus (laziness is a virtue in programming right?). Ill reopen this if I cant.
