### ISSUE TITLE
HTTP 403 when trying to stream mp3 from uploads.wikimedia.org

### ISSUE THREAD

**Issue by PlexSheep** [aschey/stream-download-rs#82]
Hello, I'm trying to build a music player for desktop that should support streaming from a jellyfin server (and local fs) and came across your library, which seems helpful. I tried to make a minimal example of audio streaming, but I keep getting a HTTP 403. 

This does not happen when using `reqwest`  directly or `curl`  on the command line, but these don't stream the file as far as I understand.

**Possible causes**
* Perhaps no user agent is set, so the server refuses?

**Minimal example**

```rs
use std::error::Error;
use std::io::Read;
use std::result::Result;

use stream_download::storage::temp::TempStorageProvider;
use stream_download::{Settings, StreamDownload};

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn Error>> {
    let mut reader = StreamDownload::new_http(
        "https://upload.wikimedia.org/wikipedia/commons/4/48/Aadama.mp3".parse()?,
        TempStorageProvider::new(),
        Settings::default(),
    )
    .await?;

    let mut buf = Vec::new();
    reader.read_to_end(&mut buf).unwrap();
    dbg!(buf);

    Ok(())
}
```

Error:
```text
Error: Custom { kind: InvalidInput, error: "error creating stream: error fetching https://upload.wikimedia.org/wikipedia/co mmons/4/48/Aadama.mp3: HTTP status client error (403 Forbidden) for url (https://upload.wikimedia.org/wikipedia/commons/4/4 8/Aadama.mp3)" }
```

This should be pretty much the documentation example of the crate.

**Comment by aschey** [comment]
Hey, thanks for the report! Interestingly, I wasn't able to reproduce your issue, but when I intentionally set the URL to something nonexistent to force an error, I did actually get the 403 instead of a 404. The error response contained the message `Error: 403, Forbidden. Please comply with the User-Agent policy: https://meta.wikimedia.org/wiki/User-Agent_policy at Sat, 24 Aug 2024 00:17:06 GMT`, so it looks like you were right about the user agent.

Check out the [client options](https://github.com/aschey/stream-download-rs/blob/main/examples/client_options.rs) example for how to modify the HTTP client (reqwest exposes a user_agent method that you can use).

This did uncover another issue though - internally we call reqwest's `error_for_status` method to return an error message to the user, but that doesn't contain the response body which is where the detailed error message usually resides. I'll have to think about a better way to expose that information to the caller.

As a side note - calling `reader.read_to_end(&mut buf)` on a single-threaded Tokio runtime won't work because that will block the task and prevent the download task from running. It's best to do blocking I/O inside `spawn_blocking`. Doing it that way on the README was an accident that I didn't even notice until now (even though it works in the multi-threaded runtime, its still a bad idea). I'll definitely fix that soon.

Thanks for inadvertently helping me find two semi-related issues! :laughing:

**Comment by PlexSheep** [comment]
Thank you for the swift reply and the doc fix! You say you were unable to reproduce my issue with the code I posted, did you mean that it just worked to stream from the wikimedia url? Good to know at least that the missing user-agent was indeed the cause. I suppose I should have read the documentation more clearly, but I only tried to make it work with the first usage example of the crate documentation. I'll try to get it to stream with the client_options, as you linked.

I agree that showing the body would be helpful for diagnosing errors resulting from wrong usage of the HTTP APIs, perhaps it is possible to show some sort of traceback instead?

It makes sense that calling `read_to_end` (which is not async) with a single thread runtime doesn't work, as I assume it keeps asynchronously downloading more of the stream. The documentation for `stream_blocking` says "Runs the provided closure on a thread where blocking is acceptable.", so they open a new thread even though the runtime itself is single-thread.

With this knowledge, I was able to make it work. Thank you again.

```rs
use std::error::Error;
use std::result::Result;
use std::time::Duration;

use reqwest::header::HeaderMap;
use reqwest::Client;
use rodio::{Decoder, OutputStream, Source};
use stream_download::http::HttpStream;
use stream_download::storage::memory::MemoryStorageProvider;
use stream_download::{Settings, StreamDownload};

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn Error>> {
    const URL: &str = "https://upload.wikimedia.org/wikipedia/commons/4/48/Aadama.mp3";

    let mut headers = HeaderMap::new();
    headers.append("User-Agent", "Beatbär Streaming Demo".parse().unwrap());

    let client = Client::builder().default_headers(headers).build()?;

    let stream = HttpStream::new(client, URL.parse()?).await?;
    let reader =
        StreamDownload::from_stream(stream, MemoryStorageProvider, Settings::default()).await?;

    // now play with rodio, or read it out
    tokio::task::spawn_blocking(move || {
        // Get an output stream handle to the default physical sound device
        let (_stream, stream_handle) = OutputStream::try_default().unwrap();
        // Decode that sound file into a source
        let source = Decoder::new(reader).unwrap();
        // Play the sound directly on the device
        stream_handle.play_raw(source.convert_samples()).unwrap();
        std::thread::sleep(Duration::from_secs(10)); // should be fine, because tokio says
                                                     // spawn_blocking happens in another thread
    })
    .await?;

    Ok(())
}
```
This streams the audio and actually plays it.

**Comment by aschey** [comment]
Glad you got it working! Just FYI, you can call `.user_agent(...)` on the `ClientBuilder` directly instead of creating a `HeaderMap`. What you have there is fine too, this way is just less verbose.

> did you mean that it just worked to stream from the wikimedia URL?

Yeah, I ran your example unchanged and didn't get the 403 error. Seems like there's maybe some kind of heuristics that they use to determine whether or not to show the error. Maybe you were getting it because more requests came from your IP, not sure.

> I agree that showing the body would be helpful for diagnosing errors resulting from wrong usage of the HTTP APIs, perhaps it is possible to show some sort of traceback instead?

Backtraces in Rust don't work automatically as in most other languages with a built-in runtime. There's some ongoing work to improve this, but it's not all available in the stable toolchain yet. Additionally, decoding the body is another async call that's potentially expensive, so it will probably need to be something the caller handles explicitly in case decoding the entire response is not desirable. I'll likely add a custom error type that gets returned instead of using `std::io::Error` everywhere.
